;;;; -*- Mode: LISP; Syntax: COMMON-LISP; Package: CL-CUNEIFORM; Base: 10 -*-
;;;; maps.lisp

;;;; Copyright (c) 2014 "the Phoeron" Colin J.E. Lupton <//thephoeron.com>
;;;; See LICENSE for additional information.

(in-package :cl-cuneiform)

(defvar *cuneiform-unicode-characters* '(#\CUNEIFORM_SIGN_A
                                         #\CUNEIFORM_SIGN_A_TIMES_A
                                         #\CUNEIFORM_SIGN_A_TIMES_BAD
                                         #\CUNEIFORM_SIGN_A_TIMES_GAN2_TENU
                                         #\CUNEIFORM_SIGN_A_TIMES_HA
                                         #\CUNEIFORM_SIGN_A_TIMES_IGI
                                         #\CUNEIFORM_SIGN_A_TIMES_LAGAR_GUNU
                                         #\CUNEIFORM_SIGN_A_TIMES_MUSH
                                         #\CUNEIFORM_SIGN_A_TIMES_SAG
                                         #\CUNEIFORM_SIGN_A2
                                         #\CUNEIFORM_SIGN_AB
                                         #\CUNEIFORM_SIGN_AB_TIMES_ASH2
                                         #\CUNEIFORM_SIGN_AB_TIMES_DUN3_GUNU
                                         #\CUNEIFORM_SIGN_AB_TIMES_GAL
                                         #\CUNEIFORM_SIGN_AB_TIMES_GAN2_TENU
                                         #\CUNEIFORM_SIGN_AB_TIMES_HA
                                         #\CUNEIFORM_SIGN_AB_TIMES_IGI_GUNU
                                         #\CUNEIFORM_SIGN_AB_TIMES_IMIN
                                         #\CUNEIFORM_SIGN_AB_TIMES_LAGAB
                                         #\CUNEIFORM_SIGN_AB_TIMES_SHESH
                                         #\CUNEIFORM_SIGN_AB_TIMES_U_PLUS_U_PLUS_U
                                         #\CUNEIFORM_SIGN_AB_GUNU
                                         #\CUNEIFORM_SIGN_AB2
                                         #\CUNEIFORM_SIGN_AB2_TIMES_BALAG
                                         #\CUNEIFORM_SIGN_AB2_TIMES_GAN2_TENU
                                         #\CUNEIFORM_SIGN_AB2_TIMES_ME_PLUS_EN
                                         #\CUNEIFORM_SIGN_AB2_TIMES_SHA3
                                         #\CUNEIFORM_SIGN_AB2_TIMES_TAK4
                                         #\CUNEIFORM_SIGN_AD
                                         #\CUNEIFORM_SIGN_AK
                                         #\CUNEIFORM_SIGN_AK_TIMES_ERIN2
                                         #\CUNEIFORM_SIGN_AK_TIMES_SHITA_PLUS_GISH
                                         #\CUNEIFORM_SIGN_AL
                                         #\CUNEIFORM_SIGN_AL_TIMES_AL
                                         #\CUNEIFORM_SIGN_AL_TIMES_DIM2
                                         #\CUNEIFORM_SIGN_AL_TIMES_GISH
                                         #\CUNEIFORM_SIGN_AL_TIMES_HA
                                         #\CUNEIFORM_SIGN_AL_TIMES_KAD3
                                         #\CUNEIFORM_SIGN_AL_TIMES_KI
                                         #\CUNEIFORM_SIGN_AL_TIMES_SHE
                                         #\CUNEIFORM_SIGN_AL_TIMES_USH
                                         #\CUNEIFORM_SIGN_ALAN
                                         #\CUNEIFORM_SIGN_ALEPH
                                         #\CUNEIFORM_SIGN_AMAR
                                         #\CUNEIFORM_SIGN_AMAR_TIMES_SHE
                                         #\CUNEIFORM_SIGN_AN
                                         #\CUNEIFORM_SIGN_AN_OVER_AN
                                         #\CUNEIFORM_SIGN_AN_THREE_TIMES
                                         #\CUNEIFORM_SIGN_AN_PLUS_NAGA_OPPOSING_AN_PLUS_NAGA
                                         #\CUNEIFORM_SIGN_AN_PLUS_NAGA_SQUARED
                                         #\CUNEIFORM_SIGN_ANSHE
                                         #\CUNEIFORM_SIGN_APIN
                                         #\CUNEIFORM_SIGN_ARAD
                                         #\CUNEIFORM_SIGN_ARAD_TIMES_KUR
                                         #\CUNEIFORM_SIGN_ARKAB
                                         #\CUNEIFORM_SIGN_ASAL2
                                         #\CUNEIFORM_SIGN_ASH
                                         #\CUNEIFORM_SIGN_ASH_ZIDA_TENU
                                         #\CUNEIFORM_SIGN_ASH_KABA_TENU
                                         #\CUNEIFORM_SIGN_ASH_OVER_ASH_TUG2_OVER_TUG2_TUG2_OVER_TUG2_PAP
                                         #\CUNEIFORM_SIGN_ASH_OVER_ASH_OVER_ASH
                                         #\CUNEIFORM_SIGN_ASH_OVER_ASH_OVER_ASH_CROSSING_ASH_OVER_ASH_OVER_ASH
                                         #\CUNEIFORM_SIGN_ASH2
                                         #\CUNEIFORM_SIGN_ASHGAB
                                         #\CUNEIFORM_SIGN_BA
                                         #\CUNEIFORM_SIGN_BAD
                                         #\CUNEIFORM_SIGN_BAG3
                                         #\CUNEIFORM_SIGN_BAHAR2
                                         #\CUNEIFORM_SIGN_BAL
                                         #\CUNEIFORM_SIGN_BAL_OVER_BAL
                                         #\CUNEIFORM_SIGN_BALAG
                                         #\CUNEIFORM_SIGN_BAR
                                         #\CUNEIFORM_SIGN_BARA2
                                         #\CUNEIFORM_SIGN_BI
                                         #\CUNEIFORM_SIGN_BI_TIMES_A
                                         #\CUNEIFORM_SIGN_BI_TIMES_GAR
                                         #\CUNEIFORM_SIGN_BI_TIMES_IGI_GUNU
                                         #\CUNEIFORM_SIGN_BU
                                         #\CUNEIFORM_SIGN_BU_OVER_BU_AB
                                         #\CUNEIFORM_SIGN_BU_OVER_BU_UN
                                         #\CUNEIFORM_SIGN_BU_CROSSING_BU
                                         #\CUNEIFORM_SIGN_BULUG
                                         #\CUNEIFORM_SIGN_BULUG_OVER_BULUG
                                         #\CUNEIFORM_SIGN_BUR
                                         #\CUNEIFORM_SIGN_BUR2
                                         #\CUNEIFORM_SIGN_DA
                                         #\CUNEIFORM_SIGN_DAG
                                         #\CUNEIFORM_SIGN_DAG_KISIM5_TIMES_A_PLUS_MASH
                                         #\CUNEIFORM_SIGN_DAG_KISIM5_TIMES_AMAR
                                         #\CUNEIFORM_SIGN_DAG_KISIM5_TIMES_BALAG
                                         #\CUNEIFORM_SIGN_DAG_KISIM5_TIMES_BI
                                         #\CUNEIFORM_SIGN_DAG_KISIM5_TIMES_GA
                                         #\CUNEIFORM_SIGN_DAG_KISIM5_TIMES_GA_PLUS_MASH
                                         #\CUNEIFORM_SIGN_DAG_KISIM5_TIMES_GI
                                         #\CUNEIFORM_SIGN_DAG_KISIM5_TIMES_GIR2
                                         #\CUNEIFORM_SIGN_DAG_KISIM5_TIMES_GUD
                                         #\CUNEIFORM_SIGN_DAG_KISIM5_TIMES_HA
                                         #\CUNEIFORM_SIGN_DAG_KISIM5_TIMES_IR
                                         #\CUNEIFORM_SIGN_DAG_KISIM5_TIMES_IR_PLUS_LU
                                         #\CUNEIFORM_SIGN_DAG_KISIM5_TIMES_KAK
                                         #\CUNEIFORM_SIGN_DAG_KISIM5_TIMES_LA
                                         #\CUNEIFORM_SIGN_DAG_KISIM5_TIMES_LU
                                         #\CUNEIFORM_SIGN_DAG_KISIM5_TIMES_LU_PLUS_MASH2
                                         #\CUNEIFORM_SIGN_DAG_KISIM5_TIMES_LUM
                                         #\CUNEIFORM_SIGN_DAG_KISIM5_TIMES_NE
                                         #\CUNEIFORM_SIGN_DAG_KISIM5_TIMES_PAP_PLUS_PAP
                                         #\CUNEIFORM_SIGN_DAG_KISIM5_TIMES_SI
                                         #\CUNEIFORM_SIGN_DAG_KISIM5_TIMES_TAK4
                                         #\CUNEIFORM_SIGN_DAG_KISIM5_TIMES_U2_PLUS_GIR2
                                         #\CUNEIFORM_SIGN_DAG_KISIM5_TIMES_USH
                                         #\CUNEIFORM_SIGN_DAM
                                         #\CUNEIFORM_SIGN_DAR
                                         #\CUNEIFORM_SIGN_DARA3
                                         #\CUNEIFORM_SIGN_DARA4
                                         #\CUNEIFORM_SIGN_DI
                                         #\CUNEIFORM_SIGN_DIB
                                         #\CUNEIFORM_SIGN_DIM
                                         #\CUNEIFORM_SIGN_DIM_TIMES_SHE
                                         #\CUNEIFORM_SIGN_DIM2
                                         #\CUNEIFORM_SIGN_DIN
                                         #\CUNEIFORM_SIGN_DIN_KASKAL_U_GUNU_DISH
                                         #\CUNEIFORM_SIGN_DISH
                                         #\CUNEIFORM_SIGN_DU
                                         #\CUNEIFORM_SIGN_DU_OVER_DU
                                         #\CUNEIFORM_SIGN_DU_GUNU
                                         #\CUNEIFORM_SIGN_DU_SHESHIG
                                         #\CUNEIFORM_SIGN_DUB
                                         #\CUNEIFORM_SIGN_DUB_TIMES_ESH2
                                         #\CUNEIFORM_SIGN_DUB2
                                         #\CUNEIFORM_SIGN_DUG
                                         #\CUNEIFORM_SIGN_DUGUD
                                         #\CUNEIFORM_SIGN_DUH
                                         #\CUNEIFORM_SIGN_DUN
                                         #\CUNEIFORM_SIGN_DUN3
                                         #\CUNEIFORM_SIGN_DUN3_GUNU
                                         #\CUNEIFORM_SIGN_DUN3_GUNU_GUNU
                                         #\CUNEIFORM_SIGN_DUN4
                                         #\CUNEIFORM_SIGN_DUR2
                                         #\CUNEIFORM_SIGN_E
                                         #\CUNEIFORM_SIGN_E_TIMES_PAP
                                         #\CUNEIFORM_SIGN_E_OVER_E_NUN_OVER_NUN
                                         #\CUNEIFORM_SIGN_E2
                                         #\CUNEIFORM_SIGN_E2_TIMES_A_PLUS_HA_PLUS_DA
                                         #\CUNEIFORM_SIGN_E2_TIMES_GAR
                                         #\CUNEIFORM_SIGN_E2_TIMES_MI
                                         #\CUNEIFORM_SIGN_E2_TIMES_SAL
                                         #\CUNEIFORM_SIGN_E2_TIMES_SHE
                                         #\CUNEIFORM_SIGN_E2_TIMES_U
                                         #\CUNEIFORM_SIGN_EDIN
                                         #\CUNEIFORM_SIGN_EGIR
                                         #\CUNEIFORM_SIGN_EL
                                         #\CUNEIFORM_SIGN_EN
                                         #\CUNEIFORM_SIGN_EN_TIMES_GAN2
                                         #\CUNEIFORM_SIGN_EN_TIMES_GAN2_TENU
                                         #\CUNEIFORM_SIGN_EN_TIMES_ME
                                         #\CUNEIFORM_SIGN_EN_CROSSING_EN
                                         #\CUNEIFORM_SIGN_EN_OPPOSING_EN
                                         #\CUNEIFORM_SIGN_EN_SQUARED
                                         #\CUNEIFORM_SIGN_EREN
                                         #\CUNEIFORM_SIGN_ERIN2
                                         #\CUNEIFORM_SIGN_ESH2
                                         #\CUNEIFORM_SIGN_EZEN
                                         #\CUNEIFORM_SIGN_EZEN_TIMES_A
                                         #\CUNEIFORM_SIGN_EZEN_TIMES_A_PLUS_LAL
                                         #\CUNEIFORM_SIGN_EZEN_TIMES_A_PLUS_LAL_TIMES_LAL
                                         #\CUNEIFORM_SIGN_EZEN_TIMES_AN
                                         #\CUNEIFORM_SIGN_EZEN_TIMES_BAD
                                         #\CUNEIFORM_SIGN_EZEN_TIMES_DUN3_GUNU
                                         #\CUNEIFORM_SIGN_EZEN_TIMES_DUN3_GUNU_GUNU
                                         #\CUNEIFORM_SIGN_EZEN_TIMES_HA
                                         #\CUNEIFORM_SIGN_EZEN_TIMES_HA_GUNU
                                         #\CUNEIFORM_SIGN_EZEN_TIMES_IGI_GUNU
                                         #\CUNEIFORM_SIGN_EZEN_TIMES_KASKAL
                                         #\CUNEIFORM_SIGN_EZEN_TIMES_KASKAL_SQUARED
                                         #\CUNEIFORM_SIGN_EZEN_TIMES_KU3
                                         #\CUNEIFORM_SIGN_EZEN_TIMES_LA
                                         #\CUNEIFORM_SIGN_EZEN_TIMES_LAL_TIMES_LAL
                                         #\CUNEIFORM_SIGN_EZEN_TIMES_LI
                                         #\CUNEIFORM_SIGN_EZEN_TIMES_LU
                                         #\CUNEIFORM_SIGN_EZEN_TIMES_U2
                                         #\CUNEIFORM_SIGN_EZEN_TIMES_UD
                                         #\CUNEIFORM_SIGN_GA
                                         #\CUNEIFORM_SIGN_GA_GUNU
                                         #\CUNEIFORM_SIGN_GA2
                                         #\CUNEIFORM_SIGN_GA2_TIMES_A_PLUS_DA_PLUS_HA
                                         #\CUNEIFORM_SIGN_GA2_TIMES_A_PLUS_HA
                                         #\CUNEIFORM_SIGN_GA2_TIMES_A_PLUS_IGI
                                         #\CUNEIFORM_SIGN_GA2_TIMES_AB2_TENU_PLUS_TAB
                                         #\CUNEIFORM_SIGN_GA2_TIMES_AN
                                         #\CUNEIFORM_SIGN_GA2_TIMES_ASH
                                         #\CUNEIFORM_SIGN_GA2_TIMES_ASH2_PLUS_GAL
                                         #\CUNEIFORM_SIGN_GA2_TIMES_BAD
                                         #\CUNEIFORM_SIGN_GA2_TIMES_BAR_PLUS_RA
                                         #\CUNEIFORM_SIGN_GA2_TIMES_BUR
                                         #\CUNEIFORM_SIGN_GA2_TIMES_BUR_PLUS_RA
                                         #\CUNEIFORM_SIGN_GA2_TIMES_DA
                                         #\CUNEIFORM_SIGN_GA2_TIMES_DI
                                         #\CUNEIFORM_SIGN_GA2_TIMES_DIM_TIMES_SHE
                                         #\CUNEIFORM_SIGN_GA2_TIMES_DUB
                                         #\CUNEIFORM_SIGN_GA2_TIMES_EL
                                         #\CUNEIFORM_SIGN_GA2_TIMES_EL_PLUS_LA
                                         #\CUNEIFORM_SIGN_GA2_TIMES_EN
                                         #\CUNEIFORM_SIGN_GA2_TIMES_EN_TIMES_GAN2_TENU
                                         #\CUNEIFORM_SIGN_GA2_TIMES_GAN2_TENU
                                         #\CUNEIFORM_SIGN_GA2_TIMES_GAR
                                         #\CUNEIFORM_SIGN_GA2_TIMES_GI
                                         #\CUNEIFORM_SIGN_GA2_TIMES_GI4
                                         #\CUNEIFORM_SIGN_GA2_TIMES_GI4_PLUS_A
                                         #\CUNEIFORM_SIGN_GA2_TIMES_GIR2_PLUS_SU
                                         #\CUNEIFORM_SIGN_GA2_TIMES_HA_PLUS_LU_PLUS_ESH2
                                         #\CUNEIFORM_SIGN_GA2_TIMES_HAL
                                         #\CUNEIFORM_SIGN_GA2_TIMES_HAL_PLUS_LA
                                         #\CUNEIFORM_SIGN_GA2_TIMES_HI_PLUS_LI
                                         #\CUNEIFORM_SIGN_GA2_TIMES_HUB2
                                         #\CUNEIFORM_SIGN_GA2_TIMES_IGI_GUNU
                                         #\CUNEIFORM_SIGN_GA2_TIMES_ISH_PLUS_HU_PLUS_ASH
                                         #\CUNEIFORM_SIGN_GA2_TIMES_KAK
                                         #\CUNEIFORM_SIGN_GA2_TIMES_KASKAL
                                         #\CUNEIFORM_SIGN_GA2_TIMES_KID
                                         #\CUNEIFORM_SIGN_GA2_TIMES_KID_PLUS_LAL
                                         #\CUNEIFORM_SIGN_GA2_TIMES_KU3_PLUS_AN
                                         #\CUNEIFORM_SIGN_GA2_TIMES_LA
                                         #\CUNEIFORM_SIGN_GA2_TIMES_ME_PLUS_EN
                                         #\CUNEIFORM_SIGN_GA2_TIMES_MI
                                         #\CUNEIFORM_SIGN_GA2_TIMES_NUN
                                         #\CUNEIFORM_SIGN_GA2_TIMES_NUN_OVER_NUN
                                         #\CUNEIFORM_SIGN_GA2_TIMES_PA
                                         #\CUNEIFORM_SIGN_GA2_TIMES_SAL
                                         #\CUNEIFORM_SIGN_GA2_TIMES_SAR
                                         #\CUNEIFORM_SIGN_GA2_TIMES_SHE
                                         #\CUNEIFORM_SIGN_GA2_TIMES_SHE_PLUS_TUR
                                         #\CUNEIFORM_SIGN_GA2_TIMES_SHID
                                         #\CUNEIFORM_SIGN_GA2_TIMES_SUM
                                         #\CUNEIFORM_SIGN_GA2_TIMES_TAK4
                                         #\CUNEIFORM_SIGN_GA2_TIMES_U
                                         #\CUNEIFORM_SIGN_GA2_TIMES_UD
                                         #\CUNEIFORM_SIGN_GA2_TIMES_UD_PLUS_DU
                                         #\CUNEIFORM_SIGN_GA2_OVER_GA2
                                         #\CUNEIFORM_SIGN_GABA
                                         #\CUNEIFORM_SIGN_GABA_CROSSING_GABA
                                         #\CUNEIFORM_SIGN_GAD
                                         #\CUNEIFORM_SIGN_GAD_OVER_GAD_GAR_OVER_GAR
                                         #\CUNEIFORM_SIGN_GAL
                                         #\CUNEIFORM_SIGN_GAL_GAD_OVER_GAD_GAR_OVER_GAR
                                         #\CUNEIFORM_SIGN_GALAM
                                         #\CUNEIFORM_SIGN_GAM
                                         #\CUNEIFORM_SIGN_GAN
                                         #\CUNEIFORM_SIGN_GAN2
                                         #\CUNEIFORM_SIGN_GAN2_TENU
                                         #\CUNEIFORM_SIGN_GAN2_OVER_GAN2
                                         #\CUNEIFORM_SIGN_GAN2_CROSSING_GAN2
                                         #\CUNEIFORM_SIGN_GAR
                                         #\CUNEIFORM_SIGN_GAR3
                                         #\CUNEIFORM_SIGN_GASHAN
                                         #\CUNEIFORM_SIGN_GESHTIN
                                         #\CUNEIFORM_SIGN_GESHTIN_TIMES_KUR
                                         #\CUNEIFORM_SIGN_GI
                                         #\CUNEIFORM_SIGN_GI_TIMES_E
                                         #\CUNEIFORM_SIGN_GI_TIMES_U
                                         #\CUNEIFORM_SIGN_GI_CROSSING_GI
                                         #\CUNEIFORM_SIGN_GI4
                                         #\CUNEIFORM_SIGN_GI4_OVER_GI4
                                         #\CUNEIFORM_SIGN_GI4_CROSSING_GI4
                                         #\CUNEIFORM_SIGN_GIDIM
                                         #\CUNEIFORM_SIGN_GIR2
                                         #\CUNEIFORM_SIGN_GIR2_GUNU
                                         #\CUNEIFORM_SIGN_GIR3
                                         #\CUNEIFORM_SIGN_GIR3_TIMES_A_PLUS_IGI
                                         #\CUNEIFORM_SIGN_GIR3_TIMES_GAN2_TENU
                                         #\CUNEIFORM_SIGN_GIR3_TIMES_IGI
                                         #\CUNEIFORM_SIGN_GIR3_TIMES_LU_PLUS_IGI
                                         #\CUNEIFORM_SIGN_GIR3_TIMES_PA
                                         #\CUNEIFORM_SIGN_GISAL
                                         #\CUNEIFORM_SIGN_GISH
                                         #\CUNEIFORM_SIGN_GISH_CROSSING_GISH
                                         #\CUNEIFORM_SIGN_GISH_TIMES_BAD
                                         #\CUNEIFORM_SIGN_GISH_TIMES_TAK4
                                         #\CUNEIFORM_SIGN_GISH_TENU
                                         #\CUNEIFORM_SIGN_GU
                                         #\CUNEIFORM_SIGN_GU_CROSSING_GU
                                         #\CUNEIFORM_SIGN_GU2
                                         #\CUNEIFORM_SIGN_GU2_TIMES_KAK
                                         #\CUNEIFORM_SIGN_GU2_TIMES_KAK_TIMES_IGI_GUNU
                                         #\CUNEIFORM_SIGN_GU2_TIMES_NUN
                                         #\CUNEIFORM_SIGN_GU2_TIMES_SAL_PLUS_TUG2
                                         #\CUNEIFORM_SIGN_GU2_GUNU
                                         #\CUNEIFORM_SIGN_GUD
                                         #\CUNEIFORM_SIGN_GUD_TIMES_A_PLUS_KUR
                                         #\CUNEIFORM_SIGN_GUD_TIMES_KUR
                                         #\CUNEIFORM_SIGN_GUD_OVER_GUD_LUGAL
                                         #\CUNEIFORM_SIGN_GUL
                                         #\CUNEIFORM_SIGN_GUM
                                         #\CUNEIFORM_SIGN_GUM_TIMES_SHE
                                         #\CUNEIFORM_SIGN_GUR
                                         #\CUNEIFORM_SIGN_GUR7
                                         #\CUNEIFORM_SIGN_GURUN
                                         #\CUNEIFORM_SIGN_GURUSH
                                         #\CUNEIFORM_SIGN_HA
                                         #\CUNEIFORM_SIGN_HA_TENU
                                         #\CUNEIFORM_SIGN_HA_GUNU
                                         #\CUNEIFORM_SIGN_HAL
                                         #\CUNEIFORM_SIGN_HI
                                         #\CUNEIFORM_SIGN_HI_TIMES_ASH
                                         #\CUNEIFORM_SIGN_HI_TIMES_ASH2
                                         #\CUNEIFORM_SIGN_HI_TIMES_BAD
                                         #\CUNEIFORM_SIGN_HI_TIMES_DISH
                                         #\CUNEIFORM_SIGN_HI_TIMES_GAD
                                         #\CUNEIFORM_SIGN_HI_TIMES_KIN
                                         #\CUNEIFORM_SIGN_HI_TIMES_NUN
                                         #\CUNEIFORM_SIGN_HI_TIMES_SHE
                                         #\CUNEIFORM_SIGN_HI_TIMES_U
                                         #\CUNEIFORM_SIGN_HU
                                         #\CUNEIFORM_SIGN_HUB2
                                         #\CUNEIFORM_SIGN_HUB2_TIMES_AN
                                         #\CUNEIFORM_SIGN_HUB2_TIMES_HAL
                                         #\CUNEIFORM_SIGN_HUB2_TIMES_KASKAL
                                         #\CUNEIFORM_SIGN_HUB2_TIMES_LISH
                                         #\CUNEIFORM_SIGN_HUB2_TIMES_UD
                                         #\CUNEIFORM_SIGN_HUL2
                                         #\CUNEIFORM_SIGN_I
                                         #\CUNEIFORM_SIGN_I_A
                                         #\CUNEIFORM_SIGN_IB
                                         #\CUNEIFORM_SIGN_IDIM
                                         #\CUNEIFORM_SIGN_IDIM_OVER_IDIM_BUR
                                         #\CUNEIFORM_SIGN_IDIM_OVER_IDIM_SQUARED
                                         #\CUNEIFORM_SIGN_IG
                                         #\CUNEIFORM_SIGN_IGI
                                         #\CUNEIFORM_SIGN_IGI_DIB
                                         #\CUNEIFORM_SIGN_IGI_RI
                                         #\CUNEIFORM_SIGN_IGI_OVER_IGI_SHIR_OVER_SHIR_UD_OVER_UD
                                         #\CUNEIFORM_SIGN_IGI_GUNU
                                         #\CUNEIFORM_SIGN_IL
                                         #\CUNEIFORM_SIGN_IL_TIMES_GAN2_TENU
                                         #\CUNEIFORM_SIGN_IL2
                                         #\CUNEIFORM_SIGN_IM
                                         #\CUNEIFORM_SIGN_IM_TIMES_TAK4
                                         #\CUNEIFORM_SIGN_IM_CROSSING_IM
                                         #\CUNEIFORM_SIGN_IM_OPPOSING_IM
                                         #\CUNEIFORM_SIGN_IM_SQUARED
                                         #\CUNEIFORM_SIGN_IMIN
                                         #\CUNEIFORM_SIGN_IN
                                         #\CUNEIFORM_SIGN_IR
                                         #\CUNEIFORM_SIGN_ISH
                                         #\CUNEIFORM_SIGN_KA
                                         #\CUNEIFORM_SIGN_KA_TIMES_A
                                         #\CUNEIFORM_SIGN_KA_TIMES_AD
                                         #\CUNEIFORM_SIGN_KA_TIMES_AD_PLUS_KU3
                                         #\CUNEIFORM_SIGN_KA_TIMES_ASH2
                                         #\CUNEIFORM_SIGN_KA_TIMES_BAD
                                         #\CUNEIFORM_SIGN_KA_TIMES_BALAG
                                         #\CUNEIFORM_SIGN_KA_TIMES_BAR
                                         #\CUNEIFORM_SIGN_KA_TIMES_BI
                                         #\CUNEIFORM_SIGN_KA_TIMES_ERIN2
                                         #\CUNEIFORM_SIGN_KA_TIMES_ESH2
                                         #\CUNEIFORM_SIGN_KA_TIMES_GA
                                         #\CUNEIFORM_SIGN_KA_TIMES_GAL
                                         #\CUNEIFORM_SIGN_KA_TIMES_GAN2_TENU
                                         #\CUNEIFORM_SIGN_KA_TIMES_GAR
                                         #\CUNEIFORM_SIGN_KA_TIMES_GAR_PLUS_SHA3_PLUS_A
                                         #\CUNEIFORM_SIGN_KA_TIMES_GI
                                         #\CUNEIFORM_SIGN_KA_TIMES_GIR2
                                         #\CUNEIFORM_SIGN_KA_TIMES_GISH_PLUS_SAR
                                         #\CUNEIFORM_SIGN_KA_TIMES_GISH_CROSSING_GISH
                                         #\CUNEIFORM_SIGN_KA_TIMES_GU
                                         #\CUNEIFORM_SIGN_KA_TIMES_GUR7
                                         #\CUNEIFORM_SIGN_KA_TIMES_IGI
                                         #\CUNEIFORM_SIGN_KA_TIMES_IM
                                         #\CUNEIFORM_SIGN_KA_TIMES_KAK
                                         #\CUNEIFORM_SIGN_KA_TIMES_KI
                                         #\CUNEIFORM_SIGN_KA_TIMES_KID
                                         #\CUNEIFORM_SIGN_KA_TIMES_LI
                                         #\CUNEIFORM_SIGN_KA_TIMES_LU
                                         #\CUNEIFORM_SIGN_KA_TIMES_ME
                                         #\CUNEIFORM_SIGN_KA_TIMES_ME_PLUS_DU
                                         #\CUNEIFORM_SIGN_KA_TIMES_ME_PLUS_GI
                                         #\CUNEIFORM_SIGN_KA_TIMES_ME_PLUS_TE
                                         #\CUNEIFORM_SIGN_KA_TIMES_MI
                                         #\CUNEIFORM_SIGN_KA_TIMES_MI_PLUS_NUNUZ
                                         #\CUNEIFORM_SIGN_KA_TIMES_NE
                                         #\CUNEIFORM_SIGN_KA_TIMES_NUN
                                         #\CUNEIFORM_SIGN_KA_TIMES_PI
                                         #\CUNEIFORM_SIGN_KA_TIMES_RU
                                         #\CUNEIFORM_SIGN_KA_TIMES_SA
                                         #\CUNEIFORM_SIGN_KA_TIMES_SAR
                                         #\CUNEIFORM_SIGN_KA_TIMES_SHA
                                         #\CUNEIFORM_SIGN_KA_TIMES_SHE
                                         #\CUNEIFORM_SIGN_KA_TIMES_SHID
                                         #\CUNEIFORM_SIGN_KA_TIMES_SHU
                                         #\CUNEIFORM_SIGN_KA_TIMES_SIG
                                         #\CUNEIFORM_SIGN_KA_TIMES_SUHUR
                                         #\CUNEIFORM_SIGN_KA_TIMES_TAR
                                         #\CUNEIFORM_SIGN_KA_TIMES_U
                                         #\CUNEIFORM_SIGN_KA_TIMES_U2
                                         #\CUNEIFORM_SIGN_KA_TIMES_UD
                                         #\CUNEIFORM_SIGN_KA_TIMES_UMUM_TIMES_PA
                                         #\CUNEIFORM_SIGN_KA_TIMES_USH
                                         #\CUNEIFORM_SIGN_KA_TIMES_ZI
                                         #\CUNEIFORM_SIGN_KA2
                                         #\CUNEIFORM_SIGN_KA2_CROSSING_KA2
                                         #\CUNEIFORM_SIGN_KAB
                                         #\CUNEIFORM_SIGN_KAD2
                                         #\CUNEIFORM_SIGN_KAD3
                                         #\CUNEIFORM_SIGN_KAD4
                                         #\CUNEIFORM_SIGN_KAD5
                                         #\CUNEIFORM_SIGN_KAD5_OVER_KAD5
                                         #\CUNEIFORM_SIGN_KAK
                                         #\CUNEIFORM_SIGN_KAK_TIMES_IGI_GUNU
                                         #\CUNEIFORM_SIGN_KAL
                                         #\CUNEIFORM_SIGN_KAL_TIMES_BAD
                                         #\CUNEIFORM_SIGN_KAL_CROSSING_KAL
                                         #\CUNEIFORM_SIGN_KAM2
                                         #\CUNEIFORM_SIGN_KAM4
                                         #\CUNEIFORM_SIGN_KASKAL
                                         #\CUNEIFORM_SIGN_KASKAL_LAGAB_TIMES_U_OVER_LAGAB_TIMES_U
                                         #\CUNEIFORM_SIGN_KASKAL_OVER_KASKAL_LAGAB_TIMES_U_OVER_LAGAB_TIMES_U
                                         #\CUNEIFORM_SIGN_KESH2
                                         #\CUNEIFORM_SIGN_KI
                                         #\CUNEIFORM_SIGN_KI_TIMES_BAD
                                         #\CUNEIFORM_SIGN_KI_TIMES_U
                                         #\CUNEIFORM_SIGN_KI_TIMES_UD
                                         #\CUNEIFORM_SIGN_KID
                                         #\CUNEIFORM_SIGN_KIN
                                         #\CUNEIFORM_SIGN_KISAL
                                         #\CUNEIFORM_SIGN_KISH
                                         #\CUNEIFORM_SIGN_KISIM5
                                         #\CUNEIFORM_SIGN_KISIM5_OVER_KISIM5
                                         #\CUNEIFORM_SIGN_KU
                                         #\CUNEIFORM_SIGN_KU_OVER_HI_TIMES_ASH2_KU_OVER_HI_TIMES_ASH2
                                         #\CUNEIFORM_SIGN_KU3
                                         #\CUNEIFORM_SIGN_KU4
                                         #\CUNEIFORM_SIGN_KU4_VARIANT_FORM
                                         #\CUNEIFORM_SIGN_KU7
                                         #\CUNEIFORM_SIGN_KUL
                                         #\CUNEIFORM_SIGN_KUL_GUNU
                                         #\CUNEIFORM_SIGN_KUN
                                         #\CUNEIFORM_SIGN_KUR
                                         #\CUNEIFORM_SIGN_KUR_OPPOSING_KUR
                                         #\CUNEIFORM_SIGN_KUSHU2
                                         #\CUNEIFORM_SIGN_KWU318
                                         #\CUNEIFORM_SIGN_LA
                                         #\CUNEIFORM_SIGN_LAGAB
                                         #\CUNEIFORM_SIGN_LAGAB_TIMES_A
                                         #\CUNEIFORM_SIGN_LAGAB_TIMES_A_PLUS_DA_PLUS_HA
                                         #\CUNEIFORM_SIGN_LAGAB_TIMES_A_PLUS_GAR
                                         #\CUNEIFORM_SIGN_LAGAB_TIMES_A_PLUS_LAL
                                         #\CUNEIFORM_SIGN_LAGAB_TIMES_AL
                                         #\CUNEIFORM_SIGN_LAGAB_TIMES_AN
                                         #\CUNEIFORM_SIGN_LAGAB_TIMES_ASH_ZIDA_TENU
                                         #\CUNEIFORM_SIGN_LAGAB_TIMES_BAD
                                         #\CUNEIFORM_SIGN_LAGAB_TIMES_BI
                                         #\CUNEIFORM_SIGN_LAGAB_TIMES_DAR
                                         #\CUNEIFORM_SIGN_LAGAB_TIMES_EN
                                         #\CUNEIFORM_SIGN_LAGAB_TIMES_GA
                                         #\CUNEIFORM_SIGN_LAGAB_TIMES_GAR
                                         #\CUNEIFORM_SIGN_LAGAB_TIMES_GUD
                                         #\CUNEIFORM_SIGN_LAGAB_TIMES_GUD_PLUS_GUD
                                         #\CUNEIFORM_SIGN_LAGAB_TIMES_HA
                                         #\CUNEIFORM_SIGN_LAGAB_TIMES_HAL
                                         #\CUNEIFORM_SIGN_LAGAB_TIMES_HI_TIMES_NUN
                                         #\CUNEIFORM_SIGN_LAGAB_TIMES_IGI_GUNU
                                         #\CUNEIFORM_SIGN_LAGAB_TIMES_IM
                                         #\CUNEIFORM_SIGN_LAGAB_TIMES_IM_PLUS_HA
                                         #\CUNEIFORM_SIGN_LAGAB_TIMES_IM_PLUS_LU
                                         #\CUNEIFORM_SIGN_LAGAB_TIMES_KI
                                         #\CUNEIFORM_SIGN_LAGAB_TIMES_KIN
                                         #\CUNEIFORM_SIGN_LAGAB_TIMES_KU3
                                         #\CUNEIFORM_SIGN_LAGAB_TIMES_KUL
                                         #\CUNEIFORM_SIGN_LAGAB_TIMES_KUL_PLUS_HI_PLUS_A
                                         #\CUNEIFORM_SIGN_LAGAB_TIMES_LAGAB
                                         #\CUNEIFORM_SIGN_LAGAB_TIMES_LISH
                                         #\CUNEIFORM_SIGN_LAGAB_TIMES_LU
                                         #\CUNEIFORM_SIGN_LAGAB_TIMES_LUL
                                         #\CUNEIFORM_SIGN_LAGAB_TIMES_ME
                                         #\CUNEIFORM_SIGN_LAGAB_TIMES_ME_PLUS_EN
                                         #\CUNEIFORM_SIGN_LAGAB_TIMES_MUSH
                                         #\CUNEIFORM_SIGN_LAGAB_TIMES_NE
                                         #\CUNEIFORM_SIGN_LAGAB_TIMES_SHE_PLUS_SUM
                                         #\CUNEIFORM_SIGN_LAGAB_TIMES_SHITA_PLUS_GISH_PLUS_ERIN2
                                         #\CUNEIFORM_SIGN_LAGAB_TIMES_SHITA_PLUS_GISH_TENU
                                         #\CUNEIFORM_SIGN_LAGAB_TIMES_SHU2
                                         #\CUNEIFORM_SIGN_LAGAB_TIMES_SHU2_PLUS_SHU2
                                         #\CUNEIFORM_SIGN_LAGAB_TIMES_SUM
                                         #\CUNEIFORM_SIGN_LAGAB_TIMES_TAG
                                         #\CUNEIFORM_SIGN_LAGAB_TIMES_TAK4
                                         #\CUNEIFORM_SIGN_LAGAB_TIMES_TE_PLUS_A_PLUS_SU_PLUS_NA
                                         #\CUNEIFORM_SIGN_LAGAB_TIMES_U
                                         #\CUNEIFORM_SIGN_LAGAB_TIMES_U_PLUS_A
                                         #\CUNEIFORM_SIGN_LAGAB_TIMES_U_PLUS_U_PLUS_U
                                         #\CUNEIFORM_SIGN_LAGAB_TIMES_U2_PLUS_ASH
                                         #\CUNEIFORM_SIGN_LAGAB_TIMES_UD
                                         #\CUNEIFORM_SIGN_LAGAB_TIMES_USH
                                         #\CUNEIFORM_SIGN_LAGAB_SQUARED
                                         #\CUNEIFORM_SIGN_LAGAR
                                         #\CUNEIFORM_SIGN_LAGAR_TIMES_SHE
                                         #\CUNEIFORM_SIGN_LAGAR_TIMES_SHE_PLUS_SUM
                                         #\CUNEIFORM_SIGN_LAGAR_GUNU
                                         #\CUNEIFORM_SIGN_LAGAR_GUNU_OVER_LAGAR_GUNU_SHE
                                         #\CUNEIFORM_SIGN_LAHSHU
                                         #\CUNEIFORM_SIGN_LAL
                                         #\CUNEIFORM_SIGN_LAL_TIMES_LAL
                                         #\CUNEIFORM_SIGN_LAM
                                         #\CUNEIFORM_SIGN_LAM_TIMES_KUR
                                         #\CUNEIFORM_SIGN_LAM_TIMES_KUR_PLUS_RU
                                         #\CUNEIFORM_SIGN_LI
                                         #\CUNEIFORM_SIGN_LIL
                                         #\CUNEIFORM_SIGN_LIMMU2
                                         #\CUNEIFORM_SIGN_LISH
                                         #\CUNEIFORM_SIGN_LU
                                         #\CUNEIFORM_SIGN_LU_TIMES_BAD
                                         #\CUNEIFORM_SIGN_LU2
                                         #\CUNEIFORM_SIGN_LU2_TIMES_AL
                                         #\CUNEIFORM_SIGN_LU2_TIMES_BAD
                                         #\CUNEIFORM_SIGN_LU2_TIMES_ESH2
                                         #\CUNEIFORM_SIGN_LU2_TIMES_ESH2_TENU
                                         #\CUNEIFORM_SIGN_LU2_TIMES_GAN2_TENU
                                         #\CUNEIFORM_SIGN_LU2_TIMES_HI_TIMES_BAD
                                         #\CUNEIFORM_SIGN_LU2_TIMES_IM
                                         #\CUNEIFORM_SIGN_LU2_TIMES_KAD2
                                         #\CUNEIFORM_SIGN_LU2_TIMES_KAD3
                                         #\CUNEIFORM_SIGN_LU2_TIMES_KAD3_PLUS_ASH
                                         #\CUNEIFORM_SIGN_LU2_TIMES_KI
                                         #\CUNEIFORM_SIGN_LU2_TIMES_LA_PLUS_ASH
                                         #\CUNEIFORM_SIGN_LU2_TIMES_LAGAB
                                         #\CUNEIFORM_SIGN_LU2_TIMES_ME_PLUS_EN
                                         #\CUNEIFORM_SIGN_LU2_TIMES_NE
                                         #\CUNEIFORM_SIGN_LU2_TIMES_NU
                                         #\CUNEIFORM_SIGN_LU2_TIMES_SI_PLUS_ASH
                                         #\CUNEIFORM_SIGN_LU2_TIMES_SIK2_PLUS_BU
                                         #\CUNEIFORM_SIGN_LU2_TIMES_TUG2
                                         #\CUNEIFORM_SIGN_LU2_TENU
                                         #\CUNEIFORM_SIGN_LU2_CROSSING_LU2
                                         #\CUNEIFORM_SIGN_LU2_OPPOSING_LU2
                                         #\CUNEIFORM_SIGN_LU2_SQUARED
                                         #\CUNEIFORM_SIGN_LU2_SHESHIG
                                         #\CUNEIFORM_SIGN_LU3
                                         #\CUNEIFORM_SIGN_LUGAL
                                         #\CUNEIFORM_SIGN_LUGAL_OVER_LUGAL
                                         #\CUNEIFORM_SIGN_LUGAL_OPPOSING_LUGAL
                                         #\CUNEIFORM_SIGN_LUGAL_SHESHIG
                                         #\CUNEIFORM_SIGN_LUH
                                         #\CUNEIFORM_SIGN_LUL
                                         #\CUNEIFORM_SIGN_LUM
                                         #\CUNEIFORM_SIGN_LUM_OVER_LUM
                                         #\CUNEIFORM_SIGN_LUM_OVER_LUM_GAR_OVER_GAR
                                         #\CUNEIFORM_SIGN_MA
                                         #\CUNEIFORM_SIGN_MA_TIMES_TAK4
                                         #\CUNEIFORM_SIGN_MA_GUNU
                                         #\CUNEIFORM_SIGN_MA2
                                         #\CUNEIFORM_SIGN_MAH
                                         #\CUNEIFORM_SIGN_MAR
                                         #\CUNEIFORM_SIGN_MASH
                                         #\CUNEIFORM_SIGN_MASH2
                                         #\CUNEIFORM_SIGN_ME
                                         #\CUNEIFORM_SIGN_MES
                                         #\CUNEIFORM_SIGN_MI
                                         #\CUNEIFORM_SIGN_MIN
                                         #\CUNEIFORM_SIGN_MU
                                         #\CUNEIFORM_SIGN_MU_OVER_MU
                                         #\CUNEIFORM_SIGN_MUG
                                         #\CUNEIFORM_SIGN_MUG_GUNU
                                         #\CUNEIFORM_SIGN_MUNSUB
                                         #\CUNEIFORM_SIGN_MURGU2
                                         #\CUNEIFORM_SIGN_MUSH
                                         #\CUNEIFORM_SIGN_MUSH_TIMES_A
                                         #\CUNEIFORM_SIGN_MUSH_TIMES_KUR
                                         #\CUNEIFORM_SIGN_MUSH_TIMES_ZA
                                         #\CUNEIFORM_SIGN_MUSH_OVER_MUSH
                                         #\CUNEIFORM_SIGN_MUSH_OVER_MUSH_TIMES_A_PLUS_NA
                                         #\CUNEIFORM_SIGN_MUSH_CROSSING_MUSH
                                         #\CUNEIFORM_SIGN_MUSH3
                                         #\CUNEIFORM_SIGN_MUSH3_TIMES_A
                                         #\CUNEIFORM_SIGN_MUSH3_TIMES_A_PLUS_DI
                                         #\CUNEIFORM_SIGN_MUSH3_TIMES_DI
                                         #\CUNEIFORM_SIGN_MUSH3_GUNU
                                         #\CUNEIFORM_SIGN_NA
                                         #\CUNEIFORM_SIGN_NA2
                                         #\CUNEIFORM_SIGN_NAGA
                                         #\CUNEIFORM_SIGN_NAGA_INVERTED
                                         #\CUNEIFORM_SIGN_NAGA_TIMES_SHU_TENU
                                         #\CUNEIFORM_SIGN_NAGA_OPPOSING_NAGA
                                         #\CUNEIFORM_SIGN_NAGAR
                                         #\CUNEIFORM_SIGN_NAM_NUTILLU
                                         #\CUNEIFORM_SIGN_NAM
                                         #\CUNEIFORM_SIGN_NAM2
                                         #\CUNEIFORM_SIGN_NE
                                         #\CUNEIFORM_SIGN_NE_TIMES_A
                                         #\CUNEIFORM_SIGN_NE_TIMES_UD
                                         #\CUNEIFORM_SIGN_NE_SHESHIG
                                         #\CUNEIFORM_SIGN_NI
                                         #\CUNEIFORM_SIGN_NI_TIMES_E
                                         #\CUNEIFORM_SIGN_NI2
                                         #\CUNEIFORM_SIGN_NIM
                                         #\CUNEIFORM_SIGN_NIM_TIMES_GAN2_TENU
                                         #\CUNEIFORM_SIGN_NIM_TIMES_GAR_PLUS_GAN2_TENU
                                         #\CUNEIFORM_SIGN_NINDA2
                                         #\CUNEIFORM_SIGN_NINDA2_TIMES_AN
                                         #\CUNEIFORM_SIGN_NINDA2_TIMES_ASH
                                         #\CUNEIFORM_SIGN_NINDA2_TIMES_ASH_PLUS_ASH
                                         #\CUNEIFORM_SIGN_NINDA2_TIMES_GUD
                                         #\CUNEIFORM_SIGN_NINDA2_TIMES_ME_PLUS_GAN2_TENU
                                         #\CUNEIFORM_SIGN_NINDA2_TIMES_NE
                                         #\CUNEIFORM_SIGN_NINDA2_TIMES_NUN
                                         #\CUNEIFORM_SIGN_NINDA2_TIMES_SHE
                                         #\CUNEIFORM_SIGN_NINDA2_TIMES_SHE_PLUS_A_AN
                                         #\CUNEIFORM_SIGN_NINDA2_TIMES_SHE_PLUS_ASH
                                         #\CUNEIFORM_SIGN_NINDA2_TIMES_SHE_PLUS_ASH_PLUS_ASH
                                         #\CUNEIFORM_SIGN_NINDA2_TIMES_U2_PLUS_ASH
                                         #\CUNEIFORM_SIGN_NINDA2_TIMES_USH
                                         #\CUNEIFORM_SIGN_NISAG
                                         #\CUNEIFORM_SIGN_NU
                                         #\CUNEIFORM_SIGN_NU11
                                         #\CUNEIFORM_SIGN_NUN
                                         #\CUNEIFORM_SIGN_NUN_LAGAR_TIMES_GAR
                                         #\CUNEIFORM_SIGN_NUN_LAGAR_TIMES_MASH
                                         #\CUNEIFORM_SIGN_NUN_LAGAR_TIMES_SAL
                                         #\CUNEIFORM_SIGN_NUN_LAGAR_TIMES_SAL_OVER_NUN_LAGAR_TIMES_SAL
                                         #\CUNEIFORM_SIGN_NUN_LAGAR_TIMES_USH
                                         #\CUNEIFORM_SIGN_NUN_TENU
                                         #\CUNEIFORM_SIGN_NUN_OVER_NUN
                                         #\CUNEIFORM_SIGN_NUN_CROSSING_NUN
                                         #\CUNEIFORM_SIGN_NUN_CROSSING_NUN_LAGAR_OVER_LAGAR
                                         #\CUNEIFORM_SIGN_NUNUZ
                                         #\CUNEIFORM_SIGN_NUNUZ_AB2_TIMES_ASHGAB
                                         #\CUNEIFORM_SIGN_NUNUZ_AB2_TIMES_BI
                                         #\CUNEIFORM_SIGN_NUNUZ_AB2_TIMES_DUG
                                         #\CUNEIFORM_SIGN_NUNUZ_AB2_TIMES_GUD
                                         #\CUNEIFORM_SIGN_NUNUZ_AB2_TIMES_IGI_GUNU
                                         #\CUNEIFORM_SIGN_NUNUZ_AB2_TIMES_KAD3
                                         #\CUNEIFORM_SIGN_NUNUZ_AB2_TIMES_LA
                                         #\CUNEIFORM_SIGN_NUNUZ_AB2_TIMES_NE
                                         #\CUNEIFORM_SIGN_NUNUZ_AB2_TIMES_SILA3
                                         #\CUNEIFORM_SIGN_NUNUZ_AB2_TIMES_U2
                                         #\CUNEIFORM_SIGN_NUNUZ_KISIM5_TIMES_BI
                                         #\CUNEIFORM_SIGN_NUNUZ_KISIM5_TIMES_BI_U
                                         #\CUNEIFORM_SIGN_PA
                                         #\CUNEIFORM_SIGN_PAD
                                         #\CUNEIFORM_SIGN_PAN
                                         #\CUNEIFORM_SIGN_PAP
                                         #\CUNEIFORM_SIGN_PESH2
                                         #\CUNEIFORM_SIGN_PI
                                         #\CUNEIFORM_SIGN_PI_TIMES_A
                                         #\CUNEIFORM_SIGN_PI_TIMES_AB
                                         #\CUNEIFORM_SIGN_PI_TIMES_BI
                                         #\CUNEIFORM_SIGN_PI_TIMES_BU
                                         #\CUNEIFORM_SIGN_PI_TIMES_E
                                         #\CUNEIFORM_SIGN_PI_TIMES_I
                                         #\CUNEIFORM_SIGN_PI_TIMES_IB
                                         #\CUNEIFORM_SIGN_PI_TIMES_U
                                         #\CUNEIFORM_SIGN_PI_TIMES_U2
                                         #\CUNEIFORM_SIGN_PI_CROSSING_PI
                                         #\CUNEIFORM_SIGN_PIRIG
                                         #\CUNEIFORM_SIGN_PIRIG_TIMES_KAL
                                         #\CUNEIFORM_SIGN_PIRIG_TIMES_UD
                                         #\CUNEIFORM_SIGN_PIRIG_TIMES_ZA
                                         #\CUNEIFORM_SIGN_PIRIG_OPPOSING_PIRIG
                                         #\CUNEIFORM_SIGN_RA
                                         #\CUNEIFORM_SIGN_RAB
                                         #\CUNEIFORM_SIGN_RI
                                         #\CUNEIFORM_SIGN_RU
                                         #\CUNEIFORM_SIGN_SA
                                         #\CUNEIFORM_SIGN_SAG_NUTILLU
                                         #\CUNEIFORM_SIGN_SAG
                                         #\CUNEIFORM_SIGN_SAG_TIMES_A
                                         #\CUNEIFORM_SIGN_SAG_TIMES_DU
                                         #\CUNEIFORM_SIGN_SAG_TIMES_DUB
                                         #\CUNEIFORM_SIGN_SAG_TIMES_HA
                                         #\CUNEIFORM_SIGN_SAG_TIMES_KAK
                                         #\CUNEIFORM_SIGN_SAG_TIMES_KUR
                                         #\CUNEIFORM_SIGN_SAG_TIMES_LUM
                                         #\CUNEIFORM_SIGN_SAG_TIMES_MI
                                         #\CUNEIFORM_SIGN_SAG_TIMES_NUN
                                         #\CUNEIFORM_SIGN_SAG_TIMES_SAL
                                         #\CUNEIFORM_SIGN_SAG_TIMES_SHID
                                         #\CUNEIFORM_SIGN_SAG_TIMES_TAB
                                         #\CUNEIFORM_SIGN_SAG_TIMES_U2
                                         #\CUNEIFORM_SIGN_SAG_TIMES_UB
                                         #\CUNEIFORM_SIGN_SAG_TIMES_UM
                                         #\CUNEIFORM_SIGN_SAG_TIMES_UR
                                         #\CUNEIFORM_SIGN_SAG_TIMES_USH
                                         #\CUNEIFORM_SIGN_SAG_OVER_SAG
                                         #\CUNEIFORM_SIGN_SAG_GUNU
                                         #\CUNEIFORM_SIGN_SAL
                                         #\CUNEIFORM_SIGN_SAL_LAGAB_TIMES_ASH2
                                         #\CUNEIFORM_SIGN_SANGA2
                                         #\CUNEIFORM_SIGN_SAR
                                         #\CUNEIFORM_SIGN_SHA
                                         #\CUNEIFORM_SIGN_SHA3
                                         #\CUNEIFORM_SIGN_SHA3_TIMES_A
                                         #\CUNEIFORM_SIGN_SHA3_TIMES_BAD
                                         #\CUNEIFORM_SIGN_SHA3_TIMES_GISH
                                         #\CUNEIFORM_SIGN_SHA3_TIMES_NE
                                         #\CUNEIFORM_SIGN_SHA3_TIMES_SHU2
                                         #\CUNEIFORM_SIGN_SHA3_TIMES_TUR
                                         #\CUNEIFORM_SIGN_SHA3_TIMES_U
                                         #\CUNEIFORM_SIGN_SHA3_TIMES_U_PLUS_A
                                         #\CUNEIFORM_SIGN_SHA6
                                         #\CUNEIFORM_SIGN_SHAB6
                                         #\CUNEIFORM_SIGN_SHAR2
                                         #\CUNEIFORM_SIGN_SHE
                                         #\CUNEIFORM_SIGN_SHE_HU
                                         #\CUNEIFORM_SIGN_SHE_OVER_SHE_GAD_OVER_GAD_GAR_OVER_GAR
                                         #\CUNEIFORM_SIGN_SHE_OVER_SHE_TAB_OVER_TAB_GAR_OVER_GAR
                                         #\CUNEIFORM_SIGN_SHEG9
                                         #\CUNEIFORM_SIGN_SHEN
                                         #\CUNEIFORM_SIGN_SHESH
                                         #\CUNEIFORM_SIGN_SHESH2
                                         #\CUNEIFORM_SIGN_SHESHLAM
                                         #\CUNEIFORM_SIGN_SHID
                                         #\CUNEIFORM_SIGN_SHID_TIMES_A
                                         #\CUNEIFORM_SIGN_SHID_TIMES_IM
                                         #\CUNEIFORM_SIGN_SHIM
                                         #\CUNEIFORM_SIGN_SHIM_TIMES_A
                                         #\CUNEIFORM_SIGN_SHIM_TIMES_BAL
                                         #\CUNEIFORM_SIGN_SHIM_TIMES_BULUG
                                         #\CUNEIFORM_SIGN_SHIM_TIMES_DIN
                                         #\CUNEIFORM_SIGN_SHIM_TIMES_GAR
                                         #\CUNEIFORM_SIGN_SHIM_TIMES_IGI
                                         #\CUNEIFORM_SIGN_SHIM_TIMES_IGI_GUNU
                                         #\CUNEIFORM_SIGN_SHIM_TIMES_KUSHU2
                                         #\CUNEIFORM_SIGN_SHIM_TIMES_LUL
                                         #\CUNEIFORM_SIGN_SHIM_TIMES_MUG
                                         #\CUNEIFORM_SIGN_SHIM_TIMES_SAL
                                         #\CUNEIFORM_SIGN_SHINIG
                                         #\CUNEIFORM_SIGN_SHIR
                                         #\CUNEIFORM_SIGN_SHIR_TENU
                                         #\CUNEIFORM_SIGN_SHIR_OVER_SHIR_BUR_OVER_BUR
                                         #\CUNEIFORM_SIGN_SHITA
                                         #\CUNEIFORM_SIGN_SHU
                                         #\CUNEIFORM_SIGN_SHU_OVER_INVERTED_SHU
                                         #\CUNEIFORM_SIGN_SHU2
                                         #\CUNEIFORM_SIGN_SHUBUR
                                         #\CUNEIFORM_SIGN_SI
                                         #\CUNEIFORM_SIGN_SI_GUNU
                                         #\CUNEIFORM_SIGN_SIG
                                         #\CUNEIFORM_SIGN_SIG4
                                         #\CUNEIFORM_SIGN_SIG4_OVER_SIG4_SHU2
                                         #\CUNEIFORM_SIGN_SIK2
                                         #\CUNEIFORM_SIGN_SILA3
                                         #\CUNEIFORM_SIGN_SU
                                         #\CUNEIFORM_SIGN_SU_OVER_SU
                                         #\CUNEIFORM_SIGN_SUD
                                         #\CUNEIFORM_SIGN_SUD2
                                         #\CUNEIFORM_SIGN_SUHUR
                                         #\CUNEIFORM_SIGN_SUM
                                         #\CUNEIFORM_SIGN_SUMASH
                                         #\CUNEIFORM_SIGN_SUR
                                         #\CUNEIFORM_SIGN_SUR9
                                         #\CUNEIFORM_SIGN_TA
                                         #\CUNEIFORM_SIGN_TA_ASTERISK
                                         #\CUNEIFORM_SIGN_TA_TIMES_HI
                                         #\CUNEIFORM_SIGN_TA_TIMES_MI
                                         #\CUNEIFORM_SIGN_TA_GUNU
                                         #\CUNEIFORM_SIGN_TAB
                                         #\CUNEIFORM_SIGN_TAB_OVER_TAB_NI_OVER_NI_DISH_OVER_DISH
                                         #\CUNEIFORM_SIGN_TAB_SQUARED
                                         #\CUNEIFORM_SIGN_TAG
                                         #\CUNEIFORM_SIGN_TAG_TIMES_BI
                                         #\CUNEIFORM_SIGN_TAG_TIMES_GUD
                                         #\CUNEIFORM_SIGN_TAG_TIMES_SHE
                                         #\CUNEIFORM_SIGN_TAG_TIMES_SHU
                                         #\CUNEIFORM_SIGN_TAG_TIMES_TUG2
                                         #\CUNEIFORM_SIGN_TAG_TIMES_UD
                                         #\CUNEIFORM_SIGN_TAK4
                                         #\CUNEIFORM_SIGN_TAR
                                         #\CUNEIFORM_SIGN_TE
                                         #\CUNEIFORM_SIGN_TE_GUNU
                                         #\CUNEIFORM_SIGN_TI
                                         #\CUNEIFORM_SIGN_TI_TENU
                                         #\CUNEIFORM_SIGN_TIL
                                         #\CUNEIFORM_SIGN_TIR
                                         #\CUNEIFORM_SIGN_TIR_TIMES_TAK4
                                         #\CUNEIFORM_SIGN_TIR_OVER_TIR
                                         #\CUNEIFORM_SIGN_TIR_OVER_TIR_GAD_OVER_GAD_GAR_OVER_GAR
                                         #\CUNEIFORM_SIGN_TU
                                         #\CUNEIFORM_SIGN_TUG2
                                         #\CUNEIFORM_SIGN_TUK
                                         #\CUNEIFORM_SIGN_TUM
                                         #\CUNEIFORM_SIGN_TUR
                                         #\CUNEIFORM_SIGN_TUR_OVER_TUR_ZA_OVER_ZA
                                         #\CUNEIFORM_SIGN_U
                                         #\CUNEIFORM_SIGN_U_GUD
                                         #\CUNEIFORM_SIGN_U_U_U
                                         #\CUNEIFORM_SIGN_U_OVER_U_PA_OVER_PA_GAR_OVER_GAR
                                         #\CUNEIFORM_SIGN_U_OVER_U_SUR_OVER_SUR
                                         #\CUNEIFORM_SIGN_U_OVER_U_U_REVERSED_OVER_U_REVERSED
                                         #\CUNEIFORM_SIGN_U2
                                         #\CUNEIFORM_SIGN_UB
                                         #\CUNEIFORM_SIGN_UD
                                         #\CUNEIFORM_SIGN_UD_KUSHU2
                                         #\CUNEIFORM_SIGN_UD_TIMES_BAD
                                         #\CUNEIFORM_SIGN_UD_TIMES_MI
                                         #\CUNEIFORM_SIGN_UD_TIMES_U_PLUS_U_PLUS_U
                                         #\CUNEIFORM_SIGN_UD_TIMES_U_PLUS_U_PLUS_U_GUNU
                                         #\CUNEIFORM_SIGN_UD_GUNU
                                         #\CUNEIFORM_SIGN_UD_SHESHIG
                                         #\CUNEIFORM_SIGN_UD_SHESHIG_TIMES_BAD
                                         #\CUNEIFORM_SIGN_UDUG
                                         #\CUNEIFORM_SIGN_UM
                                         #\CUNEIFORM_SIGN_UM_TIMES_LAGAB
                                         #\CUNEIFORM_SIGN_UM_TIMES_ME_PLUS_DA
                                         #\CUNEIFORM_SIGN_UM_TIMES_SHA3
                                         #\CUNEIFORM_SIGN_UM_TIMES_U
                                         #\CUNEIFORM_SIGN_UMBIN
                                         #\CUNEIFORM_SIGN_UMUM
                                         #\CUNEIFORM_SIGN_UMUM_TIMES_KASKAL
                                         #\CUNEIFORM_SIGN_UMUM_TIMES_PA
                                         #\CUNEIFORM_SIGN_UN
                                         #\CUNEIFORM_SIGN_UN_GUNU
                                         #\CUNEIFORM_SIGN_UR
                                         #\CUNEIFORM_SIGN_UR_CROSSING_UR
                                         #\CUNEIFORM_SIGN_UR_SHESHIG
                                         #\CUNEIFORM_SIGN_UR2
                                         #\CUNEIFORM_SIGN_UR2_TIMES_A_PLUS_HA
                                         #\CUNEIFORM_SIGN_UR2_TIMES_A_PLUS_NA
                                         #\CUNEIFORM_SIGN_UR2_TIMES_AL
                                         #\CUNEIFORM_SIGN_UR2_TIMES_HA
                                         #\CUNEIFORM_SIGN_UR2_TIMES_NUN
                                         #\CUNEIFORM_SIGN_UR2_TIMES_U2
                                         #\CUNEIFORM_SIGN_UR2_TIMES_U2_PLUS_ASH
                                         #\CUNEIFORM_SIGN_UR2_TIMES_U2_PLUS_BI
                                         #\CUNEIFORM_SIGN_UR4
                                         #\CUNEIFORM_SIGN_URI
                                         #\CUNEIFORM_SIGN_URI3
                                         #\CUNEIFORM_SIGN_URU
                                         #\CUNEIFORM_SIGN_URU_TIMES_A
                                         #\CUNEIFORM_SIGN_URU_TIMES_ASHGAB
                                         #\CUNEIFORM_SIGN_URU_TIMES_BAR
                                         #\CUNEIFORM_SIGN_URU_TIMES_DUN
                                         #\CUNEIFORM_SIGN_URU_TIMES_GA
                                         #\CUNEIFORM_SIGN_URU_TIMES_GAL
                                         #\CUNEIFORM_SIGN_URU_TIMES_GAN2_TENU
                                         #\CUNEIFORM_SIGN_URU_TIMES_GAR
                                         #\CUNEIFORM_SIGN_URU_TIMES_GU
                                         #\CUNEIFORM_SIGN_URU_TIMES_HA
                                         #\CUNEIFORM_SIGN_URU_TIMES_IGI
                                         #\CUNEIFORM_SIGN_URU_TIMES_IM
                                         #\CUNEIFORM_SIGN_URU_TIMES_ISH
                                         #\CUNEIFORM_SIGN_URU_TIMES_KI
                                         #\CUNEIFORM_SIGN_URU_TIMES_LUM
                                         #\CUNEIFORM_SIGN_URU_TIMES_MIN
                                         #\CUNEIFORM_SIGN_URU_TIMES_PA
                                         #\CUNEIFORM_SIGN_URU_TIMES_SHE
                                         #\CUNEIFORM_SIGN_URU_TIMES_SIG4
                                         #\CUNEIFORM_SIGN_URU_TIMES_TU
                                         #\CUNEIFORM_SIGN_URU_TIMES_U_PLUS_GUD
                                         #\CUNEIFORM_SIGN_URU_TIMES_UD
                                         #\CUNEIFORM_SIGN_URU_TIMES_URUDA
                                         #\CUNEIFORM_SIGN_URUDA
                                         #\CUNEIFORM_SIGN_URUDA_TIMES_U
                                         #\CUNEIFORM_SIGN_USH
                                         #\CUNEIFORM_SIGN_USH_TIMES_A
                                         #\CUNEIFORM_SIGN_USH_TIMES_KU
                                         #\CUNEIFORM_SIGN_USH_TIMES_KUR
                                         #\CUNEIFORM_SIGN_USH_TIMES_TAK4
                                         #\CUNEIFORM_SIGN_USHX
                                         #\CUNEIFORM_SIGN_USH2
                                         #\CUNEIFORM_SIGN_USHUMX
                                         #\CUNEIFORM_SIGN_UTUKI
                                         #\CUNEIFORM_SIGN_UZ3
                                         #\CUNEIFORM_SIGN_UZ3_TIMES_KASKAL
                                         #\CUNEIFORM_SIGN_UZU
                                         #\CUNEIFORM_SIGN_ZA
                                         #\CUNEIFORM_SIGN_ZA_TENU
                                         #\CUNEIFORM_SIGN_ZA_SQUARED_TIMES_KUR
                                         #\CUNEIFORM_SIGN_ZAG
                                         #\CUNEIFORM_SIGN_ZAMX
                                         #\CUNEIFORM_SIGN_ZE2
                                         #\CUNEIFORM_SIGN_ZI
                                         #\CUNEIFORM_SIGN_ZI_OVER_ZI
                                         #\CUNEIFORM_SIGN_ZI3
                                         #\CUNEIFORM_SIGN_ZIB
                                         #\CUNEIFORM_SIGN_ZIB_KABA_TENU
                                         #\CUNEIFORM_SIGN_ZIG
                                         #\CUNEIFORM_SIGN_ZIZ2
                                         #\CUNEIFORM_SIGN_ZU
                                         #\CUNEIFORM_SIGN_ZU5
                                         #\CUNEIFORM_SIGN_ZU5_TIMES_A
                                         #\CUNEIFORM_SIGN_ZUBUR
                                         #\CUNEIFORM_SIGN_ZUM
                                         #\CUNEIFORM_NUMERIC_SIGN_TWO_ASH
                                         #\CUNEIFORM_NUMERIC_SIGN_THREE_ASH
                                         #\CUNEIFORM_NUMERIC_SIGN_FOUR_ASH
                                         #\CUNEIFORM_NUMERIC_SIGN_FIVE_ASH
                                         #\CUNEIFORM_NUMERIC_SIGN_SIX_ASH
                                         #\CUNEIFORM_NUMERIC_SIGN_SEVEN_ASH
                                         #\CUNEIFORM_NUMERIC_SIGN_EIGHT_ASH
                                         #\CUNEIFORM_NUMERIC_SIGN_NINE_ASH
                                         #\CUNEIFORM_NUMERIC_SIGN_THREE_DISH
                                         #\CUNEIFORM_NUMERIC_SIGN_FOUR_DISH
                                         #\CUNEIFORM_NUMERIC_SIGN_FIVE_DISH
                                         #\CUNEIFORM_NUMERIC_SIGN_SIX_DISH
                                         #\CUNEIFORM_NUMERIC_SIGN_SEVEN_DISH
                                         #\CUNEIFORM_NUMERIC_SIGN_EIGHT_DISH
                                         #\CUNEIFORM_NUMERIC_SIGN_NINE_DISH
                                         #\CUNEIFORM_NUMERIC_SIGN_FOUR_U
                                         #\CUNEIFORM_NUMERIC_SIGN_FIVE_U
                                         #\CUNEIFORM_NUMERIC_SIGN_SIX_U
                                         #\CUNEIFORM_NUMERIC_SIGN_SEVEN_U
                                         #\CUNEIFORM_NUMERIC_SIGN_EIGHT_U
                                         #\CUNEIFORM_NUMERIC_SIGN_NINE_U
                                         #\CUNEIFORM_NUMERIC_SIGN_ONE_GESH2
                                         #\CUNEIFORM_NUMERIC_SIGN_TWO_GESH2
                                         #\CUNEIFORM_NUMERIC_SIGN_THREE_GESH2
                                         #\CUNEIFORM_NUMERIC_SIGN_FOUR_GESH2
                                         #\CUNEIFORM_NUMERIC_SIGN_FIVE_GESH2
                                         #\CUNEIFORM_NUMERIC_SIGN_SIX_GESH2
                                         #\CUNEIFORM_NUMERIC_SIGN_SEVEN_GESH2
                                         #\CUNEIFORM_NUMERIC_SIGN_EIGHT_GESH2
                                         #\CUNEIFORM_NUMERIC_SIGN_NINE_GESH2
                                         #\CUNEIFORM_NUMERIC_SIGN_ONE_GESHU
                                         #\CUNEIFORM_NUMERIC_SIGN_TWO_GESHU
                                         #\CUNEIFORM_NUMERIC_SIGN_THREE_GESHU
                                         #\CUNEIFORM_NUMERIC_SIGN_FOUR_GESHU
                                         #\CUNEIFORM_NUMERIC_SIGN_FIVE_GESHU
                                         #\CUNEIFORM_NUMERIC_SIGN_TWO_SHAR2
                                         #\CUNEIFORM_NUMERIC_SIGN_THREE_SHAR2
                                         #\CUNEIFORM_NUMERIC_SIGN_THREE_SHAR2_VARIANT_FORM
                                         #\CUNEIFORM_NUMERIC_SIGN_FOUR_SHAR2
                                         #\CUNEIFORM_NUMERIC_SIGN_FIVE_SHAR2
                                         #\CUNEIFORM_NUMERIC_SIGN_SIX_SHAR2
                                         #\CUNEIFORM_NUMERIC_SIGN_SEVEN_SHAR2
                                         #\CUNEIFORM_NUMERIC_SIGN_EIGHT_SHAR2
                                         #\CUNEIFORM_NUMERIC_SIGN_NINE_SHAR2
                                         #\CUNEIFORM_NUMERIC_SIGN_ONE_SHARU
                                         #\CUNEIFORM_NUMERIC_SIGN_TWO_SHARU
                                         #\CUNEIFORM_NUMERIC_SIGN_THREE_SHARU
                                         #\CUNEIFORM_NUMERIC_SIGN_THREE_SHARU_VARIANT_FORM
                                         #\CUNEIFORM_NUMERIC_SIGN_FOUR_SHARU
                                         #\CUNEIFORM_NUMERIC_SIGN_FIVE_SHARU
                                         #\CUNEIFORM_NUMERIC_SIGN_SHAR2_TIMES_GAL_PLUS_DISH
                                         #\CUNEIFORM_NUMERIC_SIGN_SHAR2_TIMES_GAL_PLUS_MIN
                                         #\CUNEIFORM_NUMERIC_SIGN_ONE_BURU
                                         #\CUNEIFORM_NUMERIC_SIGN_TWO_BURU
                                         #\CUNEIFORM_NUMERIC_SIGN_THREE_BURU
                                         #\CUNEIFORM_NUMERIC_SIGN_THREE_BURU_VARIANT_FORM
                                         #\CUNEIFORM_NUMERIC_SIGN_FOUR_BURU
                                         #\CUNEIFORM_NUMERIC_SIGN_FIVE_BURU
                                         #\CUNEIFORM_NUMERIC_SIGN_THREE_VARIANT_FORM_ESH16
                                         #\CUNEIFORM_NUMERIC_SIGN_THREE_VARIANT_FORM_ESH21
                                         #\CUNEIFORM_NUMERIC_SIGN_FOUR_VARIANT_FORM_LIMMU
                                         #\CUNEIFORM_NUMERIC_SIGN_FOUR_VARIANT_FORM_LIMMU4
                                         #\CUNEIFORM_NUMERIC_SIGN_FOUR_VARIANT_FORM_LIMMU_A
                                         #\CUNEIFORM_NUMERIC_SIGN_FOUR_VARIANT_FORM_LIMMU_B
                                         #\CUNEIFORM_NUMERIC_SIGN_SIX_VARIANT_FORM_ASH9
                                         #\CUNEIFORM_NUMERIC_SIGN_SEVEN_VARIANT_FORM_IMIN3
                                         #\CUNEIFORM_NUMERIC_SIGN_SEVEN_VARIANT_FORM_IMIN_A
                                         #\CUNEIFORM_NUMERIC_SIGN_SEVEN_VARIANT_FORM_IMIN_B
                                         #\CUNEIFORM_NUMERIC_SIGN_EIGHT_VARIANT_FORM_USSU
                                         #\CUNEIFORM_NUMERIC_SIGN_EIGHT_VARIANT_FORM_USSU3
                                         #\CUNEIFORM_NUMERIC_SIGN_NINE_VARIANT_FORM_ILIMMU
                                         #\CUNEIFORM_NUMERIC_SIGN_NINE_VARIANT_FORM_ILIMMU3
                                         #\CUNEIFORM_NUMERIC_SIGN_NINE_VARIANT_FORM_ILIMMU4
                                         #\CUNEIFORM_NUMERIC_SIGN_NINE_VARIANT_FORM_ILIMMU_A
                                         #\CUNEIFORM_NUMERIC_SIGN_TWO_ASH_TENU
                                         #\CUNEIFORM_NUMERIC_SIGN_THREE_ASH_TENU
                                         #\CUNEIFORM_NUMERIC_SIGN_FOUR_ASH_TENU
                                         #\CUNEIFORM_NUMERIC_SIGN_FIVE_ASH_TENU
                                         #\CUNEIFORM_NUMERIC_SIGN_SIX_ASH_TENU
                                         #\CUNEIFORM_NUMERIC_SIGN_ONE_BAN2
                                         #\CUNEIFORM_NUMERIC_SIGN_TWO_BAN2
                                         #\CUNEIFORM_NUMERIC_SIGN_THREE_BAN2
                                         #\CUNEIFORM_NUMERIC_SIGN_FOUR_BAN2
                                         #\CUNEIFORM_NUMERIC_SIGN_FOUR_BAN2_VARIANT_FORM
                                         #\CUNEIFORM_NUMERIC_SIGN_FIVE_BAN2
                                         #\CUNEIFORM_NUMERIC_SIGN_FIVE_BAN2_VARIANT_FORM
                                         #\CUNEIFORM_NUMERIC_SIGN_NIGIDAMIN
                                         #\CUNEIFORM_NUMERIC_SIGN_NIGIDAESH
                                         #\CUNEIFORM_NUMERIC_SIGN_ONE_ESHE3
                                         #\CUNEIFORM_NUMERIC_SIGN_TWO_ESHE3
                                         #\CUNEIFORM_NUMERIC_SIGN_ONE_THIRD_DISH
                                         #\CUNEIFORM_NUMERIC_SIGN_TWO_THIRDS_DISH
                                         #\CUNEIFORM_NUMERIC_SIGN_FIVE_SIXTHS_DISH
                                         #\CUNEIFORM_NUMERIC_SIGN_ONE_THIRD_VARIANT_FORM_A
                                         #\CUNEIFORM_NUMERIC_SIGN_TWO_THIRDS_VARIANT_FORM_A
                                         #\CUNEIFORM_NUMERIC_SIGN_ONE_EIGHTH_ASH
                                         #\CUNEIFORM_NUMERIC_SIGN_ONE_QUARTER_ASH
                                         #\CUNEIFORM_NUMERIC_SIGN_OLD_ASSYRIAN_ONE_SIXTH
                                         #\CUNEIFORM_NUMERIC_SIGN_OLD_ASSYRIAN_ONE_QUARTER
                                         #\CUNEIFORM_PUNCTUATION_SIGN_OLD_ASSYRIAN_WORD_DIVIDER
                                         #\CUNEIFORM_PUNCTUATION_SIGN_VERTICAL_COLON
                                         #\CUNEIFORM_PUNCTUATION_SIGN_DIAGONAL_COLON
                                         #\CUNEIFORM_PUNCTUATION_SIGN_DIAGONAL_TRICOLON))

;; EOF
